import './globals.css';

export const metadata = {
	title: 'Restaurant Table Booking',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className="font-lato antialiased text-black bg-white">
				<main className="relative flex justify-center items-center flex-col mx-auto">
					{children}
				</main>
			</body>
		</html>
	);
}
